export const xd = {
  data: {
    id: 1,
    attributes: {
      createdAt: "2022-02-03T16:00:04.658Z",
      updatedAt: "2022-02-03T23:28:59.549Z",
      title: "3 Morning Habits That Are Significantly Improving My Life",
      description:
        "Leverage your =mornin= to **become** the best _version_ of yourself.\n<font color='red'>test blue color font</font>\n",
      date: "2022-02-03",
      slug: "3-morning-habits-that-are-significantly-improving-my-life",
      content: [
        {
          id: 1,
          __component: "blog.text",
          text: "==I believe habits are the key to success in everything we do.==\n\nI also believe that leveraging the morning is the best way to grow and become the best versions of ourselves. The morning sets the tone for the day and is the foundation upon which the rest of the day builds. Therefore, we want to ensure we include practices that will benefit us.\n\nHere are the three morning habits that are significantly improving my life.",
        },
        { id: 1, __component: "blog.separator" },
        {
          id: 2,
          __component: "blog.text",
          text: "# Black Coffee with Mushrooms\n\nCoffee will always be my favorite morning habit.\n\nAnd to be honest, I think it’s the healthiest morning habit there is, when approached in the right way.\n\n[Coffee is incredibly healthy](https://medium.com/the-ascent/3-morning-habits-that-are-significantly-improving-my-life-9278f183b313). It has consistently been linked to so many positive health outcomes, from improved exercise performance and fat loss to a reduced risk of Alzheimer’s and reduced mortality in general.\n\nBut beyond all the health benefits, I just love coffee. It’s what gets me out of bed in the morning. I love it so much, my best friend is genuinely concerned about me because I can’t go a day without at least two cups.\n\nBut I’m smart about my coffee drinking. I don’t drink it for the caffeine (although caffeinated writing sessions are by far the best), I just love the process of making it. And each month, I take a whole week off caffeinated coffee and just drink decaf. This is crucial for ensuring you’re the boss of the coffee and not the other way around. We should never need coffee.\n\nFurthermore, we need to drink it at the right time. Don’t wake up and suck back a cup of coffee right away. Wait at least an hour after waking.\nTo make this habit even more life-changing, I add a blend of functional mushrooms to my morning cup. I use the New Zealand-based brand Flow State and can’t recommend them enough. However, if you’re North American-based I recommend Four Sigmatic, which I have also used.\n\nFunctional mushrooms may be the best superfood in existence; it seems like they do everything. And the coolest thing about them is they’re classified as an adaptogen, meaning they work in the way you need them to — in a “non-specific” way. You and I could both put this mushroom blend in our coffee, and they might work through different mechanisms in our bodies to bring us back to baseline.\n\nIf you want to dive deeper into the power of these little superfoods and how you can include them in your routine, check out [this article](https://medium.com/the-ascent/3-morning-habits-that-are-significantly-improving-my-life-9278f183b313).\n\n**Takeaway**: Black coffee has myriad health benefits, and combining this with functional mushrooms is a great way to support your overall health.\n",
        },
        {
          id: 3,
          __component: "blog.text",
          text: "# Yoga\nEvery morning as soon as I get out of bed, I get dressed and roll out my yoga mat.\n\n\nYoga is a relatively new practice for me — something I’ve only started in the last 7–8 months. However, it is changing my life.\nSince taking up this practice, my physical strength has improved, my mobility has improved, I feel better in my body, and I start my day feeling grounded.\nI love waking up and getting my muscles working and my joints moving. This practice brings me into the present moment while also setting me up, both physically and mentally, for the day ahead.\n\nIt also acts as a primer for my daily writing session.\n\nMoving our bodies is so important. But more than that, yoga brings our attention to our breath and teaches us to breathe through adversity.\n\nMovement also allows deep access into who we are, and what it’s like to be in this body, right now. You can’t help but feel the breath going in and out of your lungs. The mat under your bare feet. The stretch of your muscles.\n\nMovement forces you to be present in this moment, within yourself.\n\nFurthermore, exercise is one of the greatest zeitgebers. Zeitgebers are cues for our circadian rhythms — things that tell these internal clocks what time it is, and subsequently what bodily functions to turn on and off and which hormones to release.\n\nOptimizing your circadian rhythm is important for every aspect of your health. Not only does it improve sleep quality, but it also supports metabolism, hormone regulation, gene expression, and brain function.",
        },
        {
          id: 1,
          __component: "blog.quote",
          text: "“A disrupted clock is the mother of all maladies, and, conversely, in most chronic diseases, clock function is compromised.” — Dr. Satchin Panda, The Circadian Code",
        },
        {
          id: 4,
          __component: "blog.text",
          text: "**Takeaway**: Morning yoga is a great way to bring awareness into your body and breath. This movement will also act as a zeitgeber and is a great way to support your circadian rhythm.",
        },
        {
          id: 1,
          __component: "blog.image",
          image: {
            data: [
              {
                id: 15,
                attributes: {
                  name: "1_NFUbaFmS4AfIs1pyntRpzg.jpeg",
                  alternativeText: "1_NFUbaFmS4AfIs1pyntRpzg.jpeg",
                  caption: "1_NFUbaFmS4AfIs1pyntRpzg.jpeg",
                  width: 700,
                  height: 464,
                  formats: {
                    thumbnail: {
                      name: "thumbnail_1_NFUbaFmS4AfIs1pyntRpzg.jpeg",
                      hash: "thumbnail_1_NF_Uba_Fm_S4_Af_Is1pynt_Rpzg_26b8f56fec",
                      ext: ".jpeg",
                      mime: "image/jpeg",
                      width: 235,
                      height: 156,
                      size: 11.41,
                      path: null,
                      url: "/uploads/thumbnail_1_NF_Uba_Fm_S4_Af_Is1pynt_Rpzg_26b8f56fec.jpeg",
                    },
                    small: {
                      name: "small_1_NFUbaFmS4AfIs1pyntRpzg.jpeg",
                      hash: "small_1_NF_Uba_Fm_S4_Af_Is1pynt_Rpzg_26b8f56fec",
                      ext: ".jpeg",
                      mime: "image/jpeg",
                      width: 500,
                      height: 331,
                      size: 40.82,
                      path: null,
                      url: "/uploads/small_1_NF_Uba_Fm_S4_Af_Is1pynt_Rpzg_26b8f56fec.jpeg",
                    },
                  },
                  hash: "1_NF_Uba_Fm_S4_Af_Is1pynt_Rpzg_26b8f56fec",
                  ext: ".jpeg",
                  mime: "image/jpeg",
                  size: 80.72,
                  url: "/uploads/1_NF_Uba_Fm_S4_Af_Is1pynt_Rpzg_26b8f56fec.jpeg",
                  previewUrl: null,
                  provider: "local",
                  provider_metadata: null,
                  createdAt: "2022-02-03T19:13:38.353Z",
                  updatedAt: "2022-02-03T19:13:38.353Z",
                },
              },
            ],
          },
        },
        { id: 2, __component: "blog.separator" },
        {
          id: 1,
          __component: "blog.description-image",
          description:
            "My parents and me. There’s another like this one where he’s smiling, but it’s blurry.\n",
          image: {
            data: {
              id: 14,
              attributes: {
                name: "1_-fiQi0XUxZPeNuJRRbrdxA.jpeg",
                alternativeText: "1_-fiQi0XUxZPeNuJRRbrdxA.jpeg",
                caption: "1_-fiQi0XUxZPeNuJRRbrdxA.jpeg",
                width: 700,
                height: 568,
                formats: {
                  thumbnail: {
                    name: "thumbnail_1_-fiQi0XUxZPeNuJRRbrdxA.jpeg",
                    hash: "thumbnail_1_fi_Qi0_X_Ux_Z_Pe_Nu_JR_Rbrdx_A_93bcf5208b",
                    ext: ".jpeg",
                    mime: "image/jpeg",
                    width: 192,
                    height: 156,
                    size: 7.96,
                    path: null,
                    url: "/uploads/thumbnail_1_fi_Qi0_X_Ux_Z_Pe_Nu_JR_Rbrdx_A_93bcf5208b.jpeg",
                  },
                  small: {
                    name: "small_1_-fiQi0XUxZPeNuJRRbrdxA.jpeg",
                    hash: "small_1_fi_Qi0_X_Ux_Z_Pe_Nu_JR_Rbrdx_A_93bcf5208b",
                    ext: ".jpeg",
                    mime: "image/jpeg",
                    width: 500,
                    height: 406,
                    size: 34.78,
                    path: null,
                    url: "/uploads/small_1_fi_Qi0_X_Ux_Z_Pe_Nu_JR_Rbrdx_A_93bcf5208b.jpeg",
                  },
                },
                hash: "1_fi_Qi0_X_Ux_Z_Pe_Nu_JR_Rbrdx_A_93bcf5208b",
                ext: ".jpeg",
                mime: "image/jpeg",
                size: 61.22,
                url: "/uploads/1_fi_Qi0_X_Ux_Z_Pe_Nu_JR_Rbrdx_A_93bcf5208b.jpeg",
                previewUrl: null,
                provider: "local",
                provider_metadata: null,
                createdAt: "2022-02-03T19:13:19.986Z",
                updatedAt: "2022-02-03T19:13:19.986Z",
              },
            },
          },
        },
        { id: 3, __component: "blog.separator" },
      ],
      image: {
        data: {
          id: 13,
          attributes: {
            name: "0_8LHpqt74TEc8SGRH.jpg",
            alternativeText: "0_8LHpqt74TEc8SGRH.jpg",
            caption: "0_8LHpqt74TEc8SGRH.jpg",
            width: 700,
            height: 1050,
            formats: {
              thumbnail: {
                name: "thumbnail_0_8LHpqt74TEc8SGRH.jpg",
                hash: "thumbnail_0_8_L_Hpqt74_T_Ec8_SGRH_c7879cbfd9",
                ext: ".jpg",
                mime: "image/jpeg",
                width: 104,
                height: 156,
                size: 4.83,
                path: null,
                url: "/uploads/thumbnail_0_8_L_Hpqt74_T_Ec8_SGRH_c7879cbfd9.jpg",
              },
              large: {
                name: "large_0_8LHpqt74TEc8SGRH.jpg",
                hash: "large_0_8_L_Hpqt74_T_Ec8_SGRH_c7879cbfd9",
                ext: ".jpg",
                mime: "image/jpeg",
                width: 667,
                height: 1000,
                size: 124.1,
                path: null,
                url: "/uploads/large_0_8_L_Hpqt74_T_Ec8_SGRH_c7879cbfd9.jpg",
              },
              medium: {
                name: "medium_0_8LHpqt74TEc8SGRH.jpg",
                hash: "medium_0_8_L_Hpqt74_T_Ec8_SGRH_c7879cbfd9",
                ext: ".jpg",
                mime: "image/jpeg",
                width: 500,
                height: 750,
                size: 74.53,
                path: null,
                url: "/uploads/medium_0_8_L_Hpqt74_T_Ec8_SGRH_c7879cbfd9.jpg",
              },
              small: {
                name: "small_0_8LHpqt74TEc8SGRH.jpg",
                hash: "small_0_8_L_Hpqt74_T_Ec8_SGRH_c7879cbfd9",
                ext: ".jpg",
                mime: "image/jpeg",
                width: 333,
                height: 500,
                size: 35.53,
                path: null,
                url: "/uploads/small_0_8_L_Hpqt74_T_Ec8_SGRH_c7879cbfd9.jpg",
              },
            },
            hash: "0_8_L_Hpqt74_T_Ec8_SGRH_c7879cbfd9",
            ext: ".jpg",
            mime: "image/jpeg",
            size: 139.46,
            url: "/uploads/0_8_L_Hpqt74_T_Ec8_SGRH_c7879cbfd9.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2022-02-03T18:54:08.507Z",
            updatedAt: "2022-02-03T18:54:08.507Z",
          },
        },
      },
      attribution: {
        id: 1,
        authorName: "Tyler Nix",
        authorLink: "https://unsplash.com/@jtylernix/collections",
        pageName: "Unsplash",
        pageLink: "https://unsplash.com/",
      },
    },
  },
  meta: {},
}
